# Generated by Django 5.2.6 on 2025-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
